# Generated by Django 3.1.3 on 2020-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarticle',
            name='processingState',
            field=models.IntegerField(default=0),
        ),
    ]
