# Generated by Django 3.1.3 on 2020-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_uploadedarticle_processingstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarticle',
            name='name',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
