# Generated by Django 3.1.3 on 2020-11-23 18:58

from django.db import migrations, models
import segmentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_uploadedarticle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedarticle',
            name='article',
            field=models.FileField(storage=segmentation.models.OverwriteStorage(), upload_to='articles'),
        ),
    ]
