# Generated by Django 3.1.3 on 2020-11-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_auto_20201123_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedarticle',
            old_name='name',
            new_name='ori_name',
        ),
    ]
