# Generated by Django 3.1.3 on 2020-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_auto_20201123_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarticle',
            name='processingStep',
            field=models.IntegerField(default=0),
        ),
    ]
