# Generated by Django 3.1.3 on 2020-12-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_uploadedarticle_processingstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentedimage',
            name='ori_article_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
