# Generated by Django 3.1.3 on 2020-12-09 13:41

from django.db import migrations, models
import segmentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0007_segmentedimage_ori_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarticle',
            name='zippedExtractedImages',
            field=models.FileField(blank=True, storage=segmentation.models.OverwriteStorage(), upload_to='archives'),
        ),
    ]
